version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
  build:
    docker:
      - image: cimg/node:18.17.0
    steps:
      - checkout
      - run: npm install

workflows:
  sample:
    jobs:
      - build
