version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
  build:
    docker:
      - image: cimg/node:18.17.0
    steps:
      - checkout
      - run: npm install
      - run:
          name: Deploy to Vercel
          command: npx vercel --token $VERCEL_TOKEN --prod
      - run:
          name: Deploy to Netlify
          command: npx netlify-cli deploy --auth $NETLIFY_TOKEN --prod

workflows:
  sample:
    jobs:
      - build
